version: '3'
services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc-db:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro

volumes:
  orthanc-db:
